name: Delete files

on:
  workflow_dispatch:

jobs:
  delete-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Delete all files
        run: |
          git rm -r *
          git commit -m "Törlés GitHub Action által"
          git push
